/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package me.fritz.creativeworlds;

import org.bukkit.GameMode;
import org.bukkit.entity.Player;
import org.bukkit.event.player.PlayerChangedWorldEvent;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerListener;
import org.bukkit.event.player.PlayerTeleportEvent;

/**
 *
 * @author fritz
 */
public class CreativeWorldsPlayerListener extends PlayerListener {
    CreativeWorlds plugin;
    
    /** Listens for Player events
     */
    public CreativeWorldsPlayerListener(CreativeWorlds instance) {
        this.plugin = instance;
    }

    /** Called by the bukkit plugin manager whenever a player changes worlds
     * 
     * @param event WeatherListenerEvent generated by bukkit
     */
    @Override
    public void onPlayerChangedWorld(PlayerChangedWorldEvent event){        
        checkGameMode(event.getPlayer());
    }

    /** Called by the bukkit plugin manager whenever a player joins the server
     * 
     * @param event WeatherListenerEvent generated by bukkit
     */
    @Override
    public void onPlayerJoin(PlayerJoinEvent event){
        checkGameMode(event.getPlayer());
    }

    /** Called by the bukkit plugin manager whenever a player teleports
     * 
     * @param event WeatherListenerEvent generated by bukkit
     */
    @Override
    public void onPlayerTeleport(PlayerTeleportEvent event){
        checkGameMode(event.getPlayer());
    }
    
    public void checkGameMode(Player player) {
        if (player.getGameMode().equals(GameMode.CREATIVE)) {
            if (!plugin.config.isCreative(player.getWorld()) ||
                !player.hasPermission("cw.creative") ) {
                
                player.setGameMode(GameMode.SURVIVAL);
            }
        }
    }
}
