# Should creativeWorlds be responsible for loading worlds?
worldManager: false

# List of worlds that support creative mode
worlds:
  world:
    mode: SURVIVAL
    environment: NORMAL
    mobs: ALL 
    
  world_nether:
    mode: SURVIVAL
    environment: NORMAL
    mobs: ALL 