# Should creativeWorlds be responsible for loading worlds?
worldManager: false

# List of worlds that support creative mode
worlds:
  - name: world
    creative: false
    environment: normal
    
  - name: world_nether
    creative: false
    environment: nether